import { Annotation } from "@langchain/langgraph";
import { BaseMessage } from "@langchain/core/messages";
import { IContextData, IRelationship, GraphExpandedThoughtNode } from "@repo/api/src/models/thoughtNode/types";

export const RefineryStateAnnotation = Annotation.Root({
  // The original ThoughtNode ID being processed
  nodeId: Annotation<string>({
    reducer: (state, update) => update ?? state,
    default: () => "",
  }),
  // The raw text or context the user provided
  content: Annotation<string>({
    reducer: (state, update) => update ?? state,
    default: () => "",
  }),
  userNuance: Annotation<string>({
    reducer: (state, update) => update ?? state,
    default: () => "",
  }),
  // LLM's conversation history / scratchpad
  messages: Annotation<BaseMessage[]>({
    reducer: (state, update) => state.concat(update),
    default: () =>[],
  }),
  // The output generated by the Analyze Node
  proposedRelationships: Annotation<IRelationship[]>({
    reducer: (state, update) => update ?? state,
    default: () =>[],
  }),
  generatedContext: Annotation<IContextData | null>({
    reducer: (state, update) => update ?? state,
    default: () => null,
  }),
  // Raw nodes retrieved from DB to be processed by Analyze Node
  retrievedContext: Annotation<GraphExpandedThoughtNode[]>({
    reducer: (state, update) => update ?? state,
    default: () => [],
  })
});

export type RefineryState = typeof RefineryStateAnnotation.State;