import { GraphEdge } from "../graphql/__generated__/types";

export class EmbeddingService {
    static async generateEmbedding(text: string): Promise<number[]> {
        // Call OpenAI / Anthropic / Local LLM here
        // return response.choices[0].message.content;
        return [0.012, -0.045, 0.088, 0.102, 0.055]; 
    }
}

export class LLMService {
    static async generateText(prompt: string): Promise<string> {
        // Call OpenAI / Anthropic / Local LLM here
        // return response.choices[0].message.content;
        return "This is a synthesized aha moment generated by the AI.";
    }
  
    static async extractSearchIntent(prompt: string): Promise<string> {
        // e.g. "I keep thinking about how dopamine affects my focus..." 
        // -> "dopamine effects on focus and attention span"
        // You can skip this and just return the prompt if you want to save API calls.
        return prompt; 
    }
    
    static async generateSynthesis(query: string, nodes: any[], edges: GraphEdge[]): Promise<string> {
      // Call OpenAI / Anthropic / Local LLM here
      // return response.choices[0].message.content;
      return "This is a synthesized aha moment generated by the AI.";
    }
}
